# Generated by Django 5.2.12 on 2026-06-11 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0004_remove_host_uniq_host_ip_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('compose_file', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTING', 'Starting'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('REMOVING', 'Removing')], default='CREATED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stacks', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='hosts.host')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'host')},
            },
        ),
    ]
