# Generated by Django 6.0.3 on 2026-03-26 23:20

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ssh_credentials',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
