# Generated by Django 5.2.12 on 2026-04-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_dedupe_hosts_add_unique_endpoint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='host',
            name='uniq_host_ip_port',
        ),
    ]
