# Generated by Django 6.0.3 on 2026-03-24 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
        ('registries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePullJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_ref', models.CharField(help_text='Full image reference, e.g. nginx:1.25-alpine', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PULLING', 'Pulling'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress_log', models.TextField(blank=True, default='', help_text='Streamed JSON progress lines from Docker daemon')),
                ('error_message', models.TextField(blank=True, help_text='Error detail if status is FAILED', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the background worker began the pull', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the pull finished or failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_pull_jobs', to='hosts.host')),
                ('registry_credential', models.ForeignKey(blank=True, help_text='Credential used for private registries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_pull_jobs', to='registries.registrycredential')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_pull_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
