# Generated by Django 6.0.3 on 2026-03-23 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text="Human-readable label, e.g. 'My DockerHub'", max_length=100)),
                ('registry_url', models.CharField(help_text='Registry endpoint, e.g. https://index.docker.io/v1/', max_length=255)),
                ('username', models.CharField(help_text='Registry login username', max_length=150)),
                ('_encrypted_token', models.TextField(db_column='encrypted_token', help_text='Fernet-encrypted password or access token')),
                ('is_default', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'alias')},
            },
        ),
    ]
