# Generated by Django 5.2.12 on 2026-06-09 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0004_remove_host_uniq_host_ip_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docker_network_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=50)),
                ('subnet', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('internal', models.BooleanField(default=False)),
                ('attachable', models.BooleanField(default=True)),
                ('labels', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='hosts.host')),
            ],
        ),
    ]
