# Generated by Django 6.0.3 on 2026-04-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_host_connection_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='connection_string',
            field=models.CharField(default='unix:///var/run/docker.sock', max_length=255),
        ),
    ]
